#更改mysql默认root密码剧本
#任务流程：
#   1、找到安装完成之后的临时密码
#   2、复制脚本文件到远程主机
#   3、将临时密码和手动设置的新密码写进脚本
#   4、运行脚本
--- 
  #找到安装完成之后的临时密码任务
  - name: find temp passwd
    shell: "{{find_temp_passwd_code}}"
    register: results
    tags: passwd

  #复制脚本文件任务
  - name: copy script file
    copy:
      src: change_root_passwd.sh
      dest: "{{change_passwd_sh}}"
    tags: passwd

  #为什么不直接使用script模块：
  #   脚本中有变量，如果使用script模块，参数不可以在ansible服务器上传入脚本
  #所以使用copy模块复制脚本到远程主机之后，使用lineinfile模块替换掉脚本中的
  #变量。

  #用临时密码的变量替换脚本中的临时密码变量任务
  - name: send temp root password to shell file
    lineinfile:
      path: "{{change_passwd_sh}}"
      regexp: '^PASSWORD='
      line: "PASSWORD={{temp_password}}"
    tags: passwd
  
  #用主任务定义的新密码的变量替换脚本中的新密码变量任务
  - name: send new root password to shell file
    lineinfile:
      path: "{{change_passwd_sh}}"
      regexp: '^New_Pass='
      line: "New_Pass={{new_pass}}"
    tags: passwd
    
  #跑脚本任务
  - name: change root password
    shell: "sh {{change_passwd_sh}}"
    tags: passwd
